//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemisionEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemisionEntrada()
        {
            this.RemisionEntradaDetalle = new HashSet<RemisionEntradaDetalle>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public int IdProveedor { get; set; }
        public int IdAlmacen { get; set; }
        public int Estado { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemisionEntradaDetalle> RemisionEntradaDetalle { get; set; }
    }
}
